// data.js
// Import Firebase modules from the SDKs you need
import { initializeApp } from "firebase/app";
import { getAnalytics } from "firebase/analytics";
import {
  getFirestore,
  collection,
  getDocs,
  doc,
  getDoc
} from "firebase/firestore";

// Your Firebase configuration (auto-generated by Firebase)
const firebaseConfig = {
  apiKey: "put me here",
  authDomain: "fput me here",
  databaseURL: "put me here",
  projectId: "put me here",
  storageBucket: "put me here",
  messagingSenderId: "put me here",
  appId: "put me here",
  measurementId: "put me here"
};


// 1) Initialize Firebase
const app = initializeApp(firebaseConfig);
// 2) Optional: Initialize Analytics (only works in certain environments)
const analytics = getAnalytics(app);
// 3) Get Firestore reference
const db = getFirestore(app);


  export const recipeDetail = [
    { 
        id: 1, 
        name: "Blackened Shrimp Tacos with Pineapple",
        category: "Mexican",
        rating: "Easy",
        time: "1 hour",
        image: "https://www.allrecipes.com/thmb/uWgYL40zm5CUQFv8BY4jK8PpKN0=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/8629864_Blackened-Shrimp-and-Pineapple-Tacos_Maura-Rawlette_4x3-6d6cff4dfbb54e958b7577db16ab8311.jpg", 
        summary: "These blackened shrimp tacos with pineapple are bright and summery.  Add sour cream if you want to cool them down a touch.",
        cost: "$15",
        prepTime: "10 minutes",
        cookTime: "15 minutes",
        totalTime: "25 minutes",
        servings: "3",
        calories: "250",
        fat: "15",
        carbs: "40",
        protein: "175",
        notes: "To heat tortillas effectively, consider using a skillet or comal for a traditional approach, a microwave with a damp cloth or paper towel for a quick fix, or an oven for larger batches or to keep them soft.",
    },
];


/**
 * Fetch all recipes from Firestore and map them
 * to the shape your React app expects.
 */
export async function getRecipeList() {
  const snapshot = await getDocs(collection(db, "recipes"));
  const recipeList = [];

  snapshot.forEach((docSnap) => {
    const data = docSnap.data();
    recipeList.push({
      id: docSnap.id,
      name: data.Title || "Untitled",
      category: data.Category || "Uncategorized",
      rating: data.Rating || "Medium", // default if no rating stored
      time: data["Total Time"] || "30 minutes",
      image: data.Image || "https://placehold.co/400", // fallback image
    });
  });

  return recipeList;
}


/**
 * Get a single recipe document by ID.
 * Make sure your Firestore has a "recipes" collection with docs keyed by recipeId.
 */
export async function getRecipeDetail(recipeId) {
  try {
    console.log("Fetching recipe detail for ID:", recipeId);
    const docRef = doc(db, "recipes", recipeId);
    const docSnap = await getDoc(docRef);

    if (docSnap.exists()) {
      console.log("Found recipe:", docSnap.data());
      return { id: docSnap.id, ...docSnap.data() };
    } else {
      console.log("No recipe found for ID:", recipeId);
      return null;
    }
  } catch (error) {
    console.log("Error fetching recipe detail:", error);
    return null;
  }
}

/**
 * Example: If you store ingredients in a subcollection:
 * /recipes/{recipeId}/ingredients
 */
export async function getIngredients(recipeId) {
  const snapshot = await getDocs(collection(db, "recipes", recipeId, "ingredients"));
  const ingredientsArray = [];
  snapshot.forEach((docSnap) => {
    ingredientsArray.push({ id: docSnap.id, ...docSnap.data() });
  });
  return ingredientsArray;
}

/**
 * Example: If you store directions in a subcollection:
 * /recipes/{recipeId}/directions
 */
export async function getDirections(recipeId) {
  const snapshot = await getDocs(collection(db, "recipes", recipeId, "directions"));
  const directionsArray = [];
  snapshot.forEach((docSnap) => {
    directionsArray.push({ id: docSnap.id, ...docSnap.data() });
  });
  return directionsArray;
}

export const pricing = [
    {
        id: 1,
        ingredient: "Smoked paprika",
        cost: "1.59",
    },
    {
        id: 2,
        ingredient: "Onion powder",
        cost: "1.75",
    },
    {
        id: 3,
        ingredient: "Dried oregano",
        cost: "1.25",
    },
    {
        id: 4,
        ingredient: "Cayenne pepper",
        cost: "2.25",
    },
    {
        id: 5,
        ingredient: "Garlic salt",
        cost: "0.75",
    },
    {
        id: 6,
        ingredient: "Ground black pepper",
        cost: "1.35",
    },
    {
        id: 7,
        ingredient: "Fresh pineapple",
        cost: "2.50",
    },
    {
        id: 8,
        ingredient: "Chopped red onions",
        cost: "0.65",
    },
    {
        id: 9,
        ingredient: "Chopped cilantro",
        cost: "0.20",
    },
    {
        id: 10,
        ingredient: "Lime",
        cost: "0.45",
    },
    {
        id: 11,
        ingredient: "Salt",
        cost: "0.75",
    },
    {
        id: 12,
        ingredient: "Large shrimp (1 pound)",
        cost: "12.95",
    },
    {
        id: 13,
        ingredient: "Butter",
        cost: "3.30",
    },
    {
        id: 14,
        ingredient: "Flour tortillas (6-6i inch)",
        cost: "4.00",
    },
];